version: "3"

services:
  facdb:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Geosupport Versions
        RELEASE: 21a
        MAJOR: 21
        MINOR: 1
        PATCH: 0
    environment:
      - BUILD_ENGINE=postgresql://postgres:postgres@localhost:5432/postgres
    volumes:
      - .:/src
    network_mode: service:db
    command: sleep infinity

  db:
    image: postgis/postgis:11-3.0-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
