name: Build

on:
  workflow_dispatch:

jobs:
  Build:
    name: Building ...
    runs-on: ubuntu-20.04
    env:
      COMPOSE_INTERACTIVE_NO_CLI: 0
    steps:
        - uses: actions/checkout@v2

        - name: Initialize
          run: ./facdb.sh init
           
        - name: Run Pipeliens
          run: |
            ./facdb.sh run -n nypl_libraries
            ./facdb.sh run -n dca_operatingbusinesses
            ./facdb.sh run -n dcp_colp
            ./facdb.sh run -n bpl_libraries
