name: Build

on:
  push:
    paths-ignore:
      - "*.md"
      - ".pre-commit-config.yml"
      - ".gitignore"
      - "docs/*"
  workflow_dispatch:

jobs:
  Build:
    name: Building ...
    runs-on: ubuntu-20.04
    steps:
        - uses: actions/checkout@v2

        - name: Initialize
          run: ./facdb.sh init

        - name: Check on Services
          run: docker-compose ps

        - name: Run Pipeliens
          run: ./facdb.sh run --all
